### PR TITLE
Enhancing Question entry in discussions

### PR DESCRIPTION
**Pull request by abdelrahman-elkady**
- Display Question Views
- Display Question Answers count
- Hovering on question owner name displays his info

### CODE REVIEW

**Comment by abdelrahman-elkady** [comment]
screenshot from 2016-03-27 19 34 55

**Comment by alihassan0** [comment]
@abdelrahman-elkady can you solve the conflicts ?

**Comment by abdelrahman-elkady** [comment]
@alihassan0 
no png

**Comment by alihassan0** [comment]
@abdelrahman-elkady

**Pull request merged**
